[project]
name = "project-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "holidays>=0.91",
    "joblib>=1.5.3",
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
    "pytest>=9.0.2",
    "requests>=2.32.5",
    "tenacity>=9.1.4",
    "typer>=0.23.1",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
tabdiff = "rates_stat.cli:app"

[tool.pytest.ini_options]
# Specifies the directories to search for tests
testpaths = ["tests"]
